### ISSUE TITLE
Missing feature: Auto update game files & backup world to different mount point

### ISSUE THREAD

**Issue by joeyb276** [jsknnr/enshrouded-server#19]
Hello,

1. Would it be possible to integrate some timed option in the image that adds maybe a Cronjob to re-run the startup command to automatically update the server files every X minutes and restart the server maybe? This way you won't have to stop/start or re-create the container to check if the game has updates.

2. Would it be possible to have a second dir and timed back-up function for the save files to the second dir? This way you can mount to a different physical disk share in case the original server files might become corrupted for any reason.

These things are merely a suggestion. Currently i'm restarting the container each day & backing up my NAS files once a week.

**Comment by jsknnr** [comment]
This would be fairly easy to implement. I would however have to rely on something like supervisor to control the stopping and starting of the enshrouded process so that the container does not die. I am not sure if I want to do that. 

My container philosophy is cattle not kittens. I don't like long lived containers and any persistent data should be backed up outside of the container.

I am not saying what you are proposing is wrong or a bad idea, it's just not how I like to do business.

If this is a feature you would love to have, check out https://github.com/mornedhels/enshrouded-server as they have already built what you are asking.

Cheers!

**Comment by bretd25** [comment]
Thank you very much for creating the container.  I am currenlty using docker compose.  What is the best way for me to ensure I have the latest server binaries. Is restarting the container enough for it to check for updates or do I need t initiate a pull to get them.  Thanks again for the creation and it works great.

**Comment by jsknnr** [comment]
The server files are not persistent by design, nor are they baked into the image. Every time the container starts it checks if it needs to download the server files.

**Comment by bretd25** [comment]
> The server files are not persistent by design, nor are they baked into the image. Every time the container starts it checks if it needs to download the server files.

Thank you for the info.  I appreciate all you have done to get my server up and running.  Thanks again.
