### ISSUE TITLE
env file or volume directory for docker compose, general ambiguity

### ISSUE THREAD

**Issue by Mitchacho** [jsknnr/enshrouded-server#41]
Thank you for putting this together. That said, I haven't been able to get it running in docker compose. Is the 0.0.0.0 IP address in the .env file the local IP or public IP? Otherwise, my container doesn't seem to recognize the correct volume path no matter what configuration changes I make. The documentation on that could be clearer on what variables to revise. Would also prefer to update the environment variables in the yaml file if possible, instead of a separate .env file. This same night, I set up Jammsen's Palworld in minutes--dunno if it's because of his documentation or because of the server resources.

**Comment by jsknnr** [comment]
The IP address variable does not need to be set, you can just leave it. That basically helps the server figure out which interface it needs to listen on, 0.0.0.0 says listen on all interfaces. It's in a container, there should really only be 1 interface for this. The only reason I added that is because some folks weren't able to get connectivity working without setting it... however, the real problem is more likely they don't have the network configured right on their docker host.

I don't use Compose or Docker and include instructions for folks who do. Compose is really meant for easily launching multiple containers in a stack. If you are just launching a single container, it's just as easy to put your container run command into a bash file and execute that. But I digress a bit. The environment variables can be included inline with the compose yaml. Just modify the file changing env_file out for environment and then listing each key and value pair for the environment variables you need to set.

My container process does not run as root. This will cause issues if the container isn't provisioned right and could be your issue with the volume. How are you attempting to mount your storage into the container? I'll take a look if you can post it.

**Comment by Mitchacho** [comment]
Thanks for the support. I like docker compose and portainer for many many reasons.

So, this is the error I'm getting:

"failed to deploy a stack: Failed to load /data/compose/83/default.env: open /data/compose/83/default.env: no such file or directory"

I've tried changing permissions for the file path in ubuntu, used default settings, making that directory path as shown in github, and also changed the path variables several different ways. Still nothing.

**Comment by jsknnr** [comment]
Can you show me your compose file and if you are still using the env file show me that too? As well as how you are calling compose and from which directory.

**Comment by miscalaneous** [comment]
> Thanks for the support. I like docker compose and portainer for many many reasons.
> 
> So, this is the error I'm getting:
> 
> "failed to deploy a stack: Failed to load /data/compose/83/default.env: open /data/compose/83/default.env: no such file or directory"
> 
> I've tried changing permissions for the file path in ubuntu, used default settings, making that directory path as shown in github, and also changed the path variables several different ways. Still nothing.

I was able to get it running with:
Navigate into your container folder
mkdir -p data/Steam data/enshrouded && chown 1000:1000 -R data
Assuming everything else was configured correctly, this would get it running.

That said, after the latest patch it the server no longer shows up in the Community List for me. I haven't tried to figure out why just yet but will look into it too when I get home.

**Comment by miscalaneous** [comment]
> That's interesting... The data for my image should be owned by 10000:10000 not 1000. You may not actually be using my image if that worked for you lol.

It's definitely your image, however I may have just made a mistake when I made those directories and didn't catch it, because for some reason it worked.
![image](https://github.com/jsknnr/enshrouded-server/assets/69340521/88292e39-412c-4af3-a4cc-2c670f9f00c2)

**Comment by miscalaneous** [comment]
Update, I changed the owner to 10000:10000, and after a bit the server is back in my community server list.
It may have just been some jank with my home network preventing it previously.

**Comment by jsknnr** [comment]
Honestly it was likely the permissions issue. Also that is an old image. Can you update the tag to be `v2.0.5` ? Alternatively, you can try my new `proton-latest` image (tag) if you'd like. Others have been seeing pretty big gains in performance with the Proton image over the Wine image.

**Comment by tophlcvf** [comment]
> Update, I changed the owner to 10000:10000, and after a bit the server is back in my community server list. It may have just been some jank with my home network preventing it previously.

hi, i got the same thing to fix in my synologie.. how to change the owner please?
