### ISSUE TITLE
Relocate savegame and game install files

### ISSUE THREAD

**Issue by Kivarnis** [jsknnr/enshrouded-server#68]
Ideally I want to be able to specify where the game files are downloaded but I -must- be able set where the savefiles go on the general system. I keep this stuff very organized on my server and not sure how I can tell it where to store these files. In my case the proper directory OUTSIDE of the container is /home/username/Enshrouded/ and savegame or serverfiles respectively.

I'm not sure how to accomplish this with this particular docker file, I was using another but experienced serious issues of game warping so decided to try this one on reccomendation.

**Comment by jsknnr** [comment]
In the container, the savegame data is at `/home/steam/enshrouded/savegame` you can bind mount a volume here. You can either have Docker/Podman provision a volume and manage that, or, you can create a directory somewhere and specify that to bind mount.  I don't typically persist the server data since that isn't important to me. You can try also bind mounting a directory to `/home/steam/enshrouded` for that.
